### ISSUE TITLE
win10

### ISSUE THREAD

**Issue by QingshuiL** [FateScript/CenterNet-better#2]
Hi! Thank you for publishing this code.But can l run the code on Windos10?

**Comment by FateScript** [comment]
> Hi! Thank you for publishing this code.But can l run the code on Windos10?

Since this repo is mainly based on detectron2, I do not officially support windows, but it probably won't take a lot of changes to run on win10.  

You may refer to [this issule](https://github.com/facebookresearch/detectron2/issues/9) to get what you need(Linux System is still highly recommended for use).

**Comment by QingshuiL** [comment]
I guess it's time for me to learn linnux.Thanks for your reply
